dist: trusty
sudo: false
language: ruby

rvm:
  - 2.5.5
  - 2.4.6

branches:
  only:
    - master

env:
  global:
    - LOCAL_BUILDS="$HOME/local-builds"
    - BOTAN_INSTALL="${LOCAL_BUILDS}/botan-install"
    - LD_LIBRARY_PATH="${BOTAN_INSTALL}/lib"
  matrix:
    - BOTAN_VERSION=2.2.0
    - BOTAN_VERSION=2.3.0
    - BOTAN_VERSION=2.4.0
    - BOTAN_VERSION=2.5.0
    - BOTAN_VERSION=2.6.0
    - BOTAN_VERSION=2.7.0
    - BOTAN_VERSION=2.8.0
    - BOTAN_VERSION=2.9.0
    - BOTAN_VERSION=2.10.0

cache:
  bundler: true
  directories:
    - "$BOTAN_INSTALL"

before_install:
  - gem install bundler -v 1.13.7
  - ./ci/install.sh

script: bundle exec rubocop && bundle exec rake
